### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by olliheadley** [PaRaMeRoS/Algorithmus#6]
https://github.com/AIIrondev/PaRaMeRoS-Algorithmus/wiki#grafikal-user-interface   needs to be changed to Graphical user interface

**Comment by AIIrondev** [comment]
> https://github.com/AIIrondev/PaRaMeRoS-Algorithmus/wiki#grafikal-user-interface   needs to be changed to Graphical user interface

I will be reworking the app soon sorry that it took so long.

**Comment by AIIrondev** [comment]
Thanks for pointing it out! It should be correctet.
